version: '3.3'

services:
  trader-site:
    container_name: trader-site
    image: ${SITE_CONTAINER_IMAGE}
    restart: always
    ports:
      - "420:18256"
    environment:
      VIRTUAL_HOST: tradersite.betavi.local
      PG_HOST: trader-db
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      CB_KEYFILE: ${CB_KEYFILE}
      # CB_URL: ${CB_URL}
      # CB_KEY: ${CB_KEY}
      # CB_SECRET: ${CB_SECRET}
      # CB_PASSPHRASE: ${CB_PASSPHRASE}
      ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - trader-db

  trader-bot:
    container_name: trader-bot
    image: ${BOT_CONTAINER_IMAGE}
    restart: always
    environment:
      LOG_RETENTION_INTERVAL: ${LOG_RETENTION_INTERVAL}
      LOG_RETENTION_FREQUENCY: ${LOG_RETENTION_FREQUENCY}
      PG_HOST: trader-db
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      # CB_KEYFILE: ${CB_KEYFILE}
      CB_API_KEY: ${CB_API_KEY}
      CB_API_SECRET: ${CB_API_SECRET}
      # CB_URL: ${CB_URL}
      # CB_KEY: ${CB_KEY}
      # CB_SECRET: ${CB_SECRET}
      # CB_PASSPHRASE: ${CB_PASSPHRASE}
      ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - trader-db

  trader-db:
    container_name: trader-db
    image: postgres:latest
    restart: always
    volumes:
      - ${DB_LOCAL_STORAGE}/traderdb:/var/lib/postgresql/data
    command: 
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "log_statement=all"
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

networks:
  default:
    external:
     name: web-server