version: '3.3'

services:
  trader-site:
    build:
      context: .
      dockerfile: ./src/site/Dockerfile
    environment:
      PG_TESTCB_HOST: trader-testcb-db
      PG_TESTCB_DATABASE: ${PG_TESTCB_DATABASE}
      PG_TESTCB_USER: ${PG_TESTCB_USER}
      PG_TESTCB_PASSWORD: ${PG_TESTCB_PASSWORD}
    depends_on:
      - trader-db
      - trader-testcb-db

  trader-bot:
    build:
      context: .
      dockerfile: ./src/bots/Dockerfile
    environment:
      PG_TESTCB_HOST: trader-testcb-db
      PG_TESTCB_DATABASE: ${PG_TESTCB_DATABASE}
      PG_TESTCB_USER: ${PG_TESTCB_USER}
      PG_TESTCB_PASSWORD: ${PG_TESTCB_PASSWORD}
    depends_on:
      - trader-db
      - trader-testcb-db

  trader-db:
    ports:
      - "1024:5432"

  trader-testcb-db:
    container_name: trader-testcb-db
    image: postgres:latest
    ports:
      - "1025:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_TESTCB_PASSWORD}
      POSTGRES_DB: ${PG_TESTCB_DATABASE}
