version: '3.3'

services:
  trader-site:
    container_name: trader-site
    image: ${SITE_CONTAINER_IMAGE}
    restart: always
    build:
      context: .
      dockerfile: ./site/Dockerfile
    ports:
      - "420:18256"
    environment:
      VIRTUAL_HOST: tradersite.betavi.local
      PG_HOST: trader-db
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      CB_URL: ${CB_URL}
      CB_KEY: ${CB_KEY}
      CB_SECRET: ${CB_SECRET}
      CB_PASSPHRASE: ${CB_PASSPHRASE}
    depends_on:
      - trader-db

  trader-bot:
    container_name: trader-bot
    image: ${BOT_CONTAINER_IMAGE}
    restart: always
    build:
      context: .
      dockerfile: ./bots/Dockerfile
    environment:
      PG_HOST: trader-db
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      CB_URL: ${CB_URL}
      CB_KEY: ${CB_KEY}
      CB_SECRET: ${CB_SECRET}
      CB_PASSPHRASE: ${CB_PASSPHRASE}
    depends_on:
      - trader-db

  trader-db:
    container_name: trader-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
